name = "food-studio-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "https://foodstudio.vn"

[[d1_databases]]
binding = "DB"
database_name = "food-studio-db-prod"
database_id = "1f7b60a1-09ce-4e61-8d31-ffd0a135e5c4"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9362092b020341a986f6c5254975f2a1"

[[kv_namespaces]]
binding = "CACHE"
id = "4bb1e1a3c82b412e815658eac787b9c7"

[[kv_namespaces]]
binding = "FEATURE_FLAGS"
id = "621a38ccbf7744738b30438a4316b3ff"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "food-studio-media-prod"

[[queues.producers]]
binding = "ORDER_EVENTS"
queue = "order-events"

[[queues.producers]]
binding = "NOTIFICATION_QUEUE"
queue = "food-studio-notification-queue"

[[queues.producers]]
binding = "SEARCH_INDEXING"
queue = "food-studio-search-indexing"

[[queues.consumers]]
queue = "order-events"
max_batch_size = 10
max_batch_timeout = 5

[durable_objects]
bindings = [
  { name = "CART", class_name = "CartDO" },
  { name = "INVENTORY_RESERVATION", class_name = "InventoryReservationDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["CartDO", "InventoryReservationDO"]

[env.staging]
name = "food-studio-api-staging"
vars = { ENVIRONMENT = "staging", CORS_ORIGIN = "https://staging.foodstudio.vn" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "food-studio-db-staging"
database_id = "73e4cb21-d81f-43f0-907b-6a567ec964cb"
